# https://github.com/actions/checkout
# https://github.com/github/super-linter
name: Super Linter
on:
  push:
    branches:
      - 'release'
      - 'experimental'
  pull_request:
    branches:
      - 'release'
      - 'experimental'
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Linter
        uses: github/super-linter@v6
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_CSHARP: true
          VALIDATE_YAML: true
          DEFAULT_BRANCH: 'release'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
